export const characterData: Character[] = [
	{
		id: 11_001,
		name: "Amy",
		image: "https://static.wikia.nocookie.net/grandchase/images/a/a7/IconHero-Amy-Hyper.png",
		tierId: 12_000,
		type: "support",
		tier: "SR",
		attr: "balance",
	},
	{
		id: 11_002,
		name: "Arme",
		image: "https://static.wikia.nocookie.net/grandchase/images/b/b3/IconHero-Arme-Hyper.png",
		tierId: 12_000,
		type: "mage",
		tier: "SR",
		attr: "retribution",
	},
	{
		id: 11_004,
		name: "Edel",
		image: "https://static.wikia.nocookie.net/grandchase/images/9/9e/IconHero-Edel-Hyper.png",
		tierId: 12_000,
		type: "assault",
		tier: "SR",
		attr: "retribution",
	},
	{
		id: 11_003,
		name: "Elesis (T)",
		image: "https://static.wikia.nocookie.net/grandchase/images/a/ad/Another-Elesis-Hyper.png",
		tierId: 12_000,
		type: "assault",
		tier: "T",
		attr: "retribution",
	},
	{
		id: 11_005,
		name: "Europa",
		image: "https://static.wikia.nocookie.net/grandchase/images/c/c7/IconHero-Europa-Hyper.png",
		tierId: 12_000,
		type: "assault",
		tier: "SR",
		attr: "cycle",
	},
	{
		id: 11_006,
		name: "Harpe",
		image: "https://static.wikia.nocookie.net/grandchase/images/2/28/IconHero-Harpe-Hyper.png",
		tierId: 12_000,
		type: "mage",
		tier: "SR",
		attr: "cycle",
	},
	{
		id: 11_007,
		name: "Hwarin (T)",
		image: "https://static.wikia.nocookie.net/grandchase/images/1/10/Another-Hwarin-Hyper.png",
		tierId: 12_000,
		type: "mage",
		tier: "T",
		attr: "balance",
	},
	{
		id: 11_008,
		name: "Io",
		image: "https://static.wikia.nocookie.net/grandchase/images/5/57/IconHero-Io-Hyper.png",
		tierId: 12_000,
		type: "ranged",
		tier: "SR",
		attr: "retribution",
	},
	{
		id: 11_009,
		name: "Jin",
		image: "https://static.wikia.nocookie.net/grandchase/images/d/dc/IconHero-Jin-Hyper.png",
		tierId: 12_000,
		type: "tank",
		tier: "SR",
		attr: "balance",
	},
	{
		id: 11_010,
		name: "Callisto (T)",
		image: "https://static.wikia.nocookie.net/grandchase/images/5/58/Another-Kalisto-Hyper.png",
		tierId: 12_000,
		type: "tank",
		tier: "T",
		attr: "retribution",
	},
	{
		id: 11_011,
		name: "Kanavan (T)",
		image: "https://static.wikia.nocookie.net/grandchase/images/e/e1/Another-Kanavan-Hyper.png",
		tierId: 12_000,
		type: "support",
		tier: "T",
		attr: "retribution",
	},
	{
		id: 11_012,
		name: "Lapis (T)",
		image: "https://static.wikia.nocookie.net/grandchase/images/d/d6/Another-Lapis-Hyper.png",
		tierId: 12_000,
		type: "assault",
		tier: "T",
		attr: "balance",
	},
	{
		id: 11_013,
		name: "Lass",
		image: "https://static.wikia.nocookie.net/grandchase/images/5/59/IconHero-Lass-Hyper.png",
		tierId: 12_000,
		type: "assault",
		tier: "SR",
		attr: "balance",
	},
	{
		id: 11_014,
		name: "Lime (T)",
		image: "https://static.wikia.nocookie.net/grandchase/images/1/19/Another-Lime-Hyper.png",
		tierId: 12_000,
		type: "tank",
		tier: "T",
		attr: "balance",
	},
	{
		id: 11_015,
		name: "Rin (T)",
		image: "https://static.wikia.nocookie.net/grandchase/images/c/c6/Another-Lin-Hyper.png",
		tierId: 12_000,
		type: "mage",
		tier: "T",
		attr: "life",
	},
	{
		id: 11_016,
		name: "Lire (T)",
		image: "https://static.wikia.nocookie.net/grandchase/images/4/4e/Another-Lire-Hyper.png",
		tierId: 12_000,
		type: "assault",
		tier: "T",
		attr: "balance",
	},
	{
		id: 11_017,
		name: "Rufus",
		image: "https://static.wikia.nocookie.net/grandchase/images/d/db/IconHero-Lupus-Hyper.png",
		tierId: 12_000,
		type: "ranged",
		tier: "SR",
		attr: "balance",
	},
	{
		id: 11_018,
		name: "Mari",
		image: "https://static.wikia.nocookie.net/grandchase/images/b/b3/IconHero-Mari-Hyper.png",
		tierId: 12_000,
		type: "mage",
		tier: "SR",
		attr: "life",
	},
	{
		id: 11_019,
		name: "Ragna (T)",
		image: "https://static.wikia.nocookie.net/grandchase/images/0/0b/Another-Ragna-Hyper.png",
		tierId: 12_000,
		type: "support",
		tier: "T",
		attr: "cycle",
	},
	{
		id: 11_020,
		name: "Rey",
		image: "https://static.wikia.nocookie.net/grandchase/images/f/f5/IconHero-Rey-Hyper.png",
		tierId: 12_000,
		type: "mage",
		tier: "SR",
		attr: "life",
	},
	{
		id: 11_021,
		name: "Ronan (T)",
		image: "https://static.wikia.nocookie.net/grandchase/images/0/09/Another-Ronan-Hyper.png",
		tierId: 12_000,
		type: "mage",
		tier: "T",
		attr: "balance",
	},
	{
		id: 11_022,
		name: "Serdin (T)",
		image: "https://static.wikia.nocookie.net/grandchase/images/e/e2/Another-Serdin-Hyper.png",
		tierId: 12_000,
		type: "mage",
		tier: "T",
		attr: "life",
	},
	{
		id: 11_023,
		name: "Sieghart",
		image: "https://static.wikia.nocookie.net/grandchase/images/e/ec/IconHero-Sieghart-Hyper.png",
		tierId: 12_000,
		type: "assault",
		tier: "SR",
		attr: "cycle",
	},
	{
		id: 11_024,
		name: "Veigas",
		image: "https://static.wikia.nocookie.net/grandchase/images/7/78/IconHero-Veigas-Hyper.png",
		tierId: 12_000,
		type: "mage",
		tier: "SR",
		attr: "balance",
	},
	{
		id: 11_025,
		name: "Werner (T)",
		image: "https://static.wikia.nocookie.net/grandchase/images/7/7a/Another-Werner-Hyper.png",
		tierId: 12_000,
		type: "assault",
		tier: "T",
		attr: "life",
	},
	{
		id: 11_026,
		name: "Zero (T)",
		image: "https://static.wikia.nocookie.net/grandchase/images/5/57/Another-Zero-Hyper.png",
		tierId: 12_000,
		type: "support",
		tier: "T",
		attr: "balance",
	},
	{
		id: 11_027,
		name: "Ai",
		image: "https://static.wikia.nocookie.net/grandchase/images/6/67/IconHero-Ai-Hyper.png",
		tierId: 12_000,
		type: "mage",
		tier: "SR",
		attr: "cycle",
	},
	{
		id: 11_028,
		name: "Amy (T)",
		image: "https://static.wikia.nocookie.net/grandchase/images/f/fc/Another-Amy-Hyper.png",
		tierId: 12_000,
		type: "assault",
		tier: "T",
		attr: "life",
	},
	{
		id: 11_029,
		name: "Arme (T)",
		image: "https://static.wikia.nocookie.net/grandchase/images/d/d6/Another-Arme-Hyper.png",
		tierId: 12_000,
		type: "support",
		tier: "T",
		attr: "ruin",
	},
	{
		id: 11_030,
		name: "Mari (T)",
		image: "https://static.wikia.nocookie.net/grandchase/images/d/dd/Another-Mari-Hyper.png",
		tierId: 12_000,
		type: "ranged",
		tier: "T",
		attr: "retribution",
	},
	{
		id: 11_031,
		name: "Mayden",
		image: "https://static.wikia.nocookie.net/grandchase/images/5/5c/IconHero-Mayden-Hyper.png",
		tierId: 12_000,
		type: "ranged",
		tier: "SR",
		attr: "life",
	},
	{
		id: 11_032,
		name: "Asin",
		image: "https://static.wikia.nocookie.net/grandchase/images/5/53/IconHero-Azin-Hyper.png",
		tierId: 12_000,
		type: "tank",
		tier: "SR",
		attr: "life",
	},
	{
		id: 11_033,
		name: "Bastet",
		image: "https://static.wikia.nocookie.net/grandchase/images/5/5c/IconHero-Bastet-Hyper.png",
		tierId: 12_000,
		type: "ranged",
		tier: "SR",
		attr: "ruin",
	},
	{
		id: 11_034,
		name: "Brammashell",
		image: "https://static.wikia.nocookie.net/grandchase/images/2/2f/IconHero-Bram-Hyper.png",
		tierId: 12_000,
		type: "assault",
		tier: "SR",
		attr: "life",
	},
	{
		id: 11_035,
		name: "Decanee",
		image: "https://static.wikia.nocookie.net/grandchase/images/8/88/IconHero-Decanee-Hyper.png",
		tierId: 12_000,
		type: "ranged",
		tier: "SR",
		attr: "ruin",
	},
	{
		id: 11_036,
		name: "Dio",
		image: "https://static.wikia.nocookie.net/grandchase/images/1/15/IconHero-Dio-Hyper.png",
		tierId: 12_000,
		type: "assault",
		tier: "SR",
		attr: "ruin",
	},
	{
		id: 11_037,
		name: "Edel (T)",
		image: "https://static.wikia.nocookie.net/grandchase/images/2/2a/Another-Edel-Hyper.png",
		tierId: 12_000,
		type: "ranged",
		tier: "T",
		attr: "retribution",
	},
	{
		id: 11_038,
		name: "Elesis",
		image: "https://static.wikia.nocookie.net/grandchase/images/f/fa/IconHero-Elesis-Hyper.png",
		tierId: 12_000,
		type: "assault",
		tier: "SR",
		attr: "life",
	},
	{
		id: 11_039,
		name: "Elesis (S)",
		image: "https://static.wikia.nocookie.net/grandchase/images/0/08/IconHero-Elesix-Special.png",
		tierId: 12_000,
		type: "assault",
		tier: "T",
		attr: "retribution",
	},
	{
		id: 11_040,
		name: "Europa (T)",
		image: "https://static.wikia.nocookie.net/grandchase/images/2/22/Another-Europa-Hyper.png",
		tierId: 12_000,
		type: "ranged",
		tier: "T",
		attr: "retribution",
	},
	{
		id: 11_041,
		name: "Ganymede",
		image: "https://static.wikia.nocookie.net/grandchase/images/e/ed/IconHero-Ganymede-Hyper.png",
		tierId: 12_000,
		type: "mage",
		tier: "SR",
		attr: "retribution",
	},
	{
		id: 11_042,
		name: "Grandiel",
		image: "https://static.wikia.nocookie.net/grandchase/images/4/47/IconHero-Grandiel-Hyper.png",
		tierId: 12_000,
		type: "support",
		tier: "SR",
		attr: "life",
	},
	{
		id: 11_043,
		name: "Harpe (T)",
		image: "https://static.wikia.nocookie.net/grandchase/images/e/eb/Another-Harpe-Hyper.png",
		tierId: 12_000,
		type: "tank",
		tier: "T",
		attr: "ruin",
	},
	{
		id: 11_044,
		name: "Hwarin",
		image: "https://static.wikia.nocookie.net/grandchase/images/0/0c/IconHero-Hwarin-Hyper.png",
		tierId: 12_000,
		type: "support",
		tier: "SR",
		attr: "balance",
	},
	{
		id: 11_045,
		name: "Io (T)",
		image: "https://static.wikia.nocookie.net/grandchase/images/e/e8/Another-Io-Hyper.png",
		tierId: 12_000,
		type: "support",
		tier: "T",
		attr: "balance",
	},
	{
		id: 11_046,
		name: "Jin (T)",
		image: "https://static.wikia.nocookie.net/grandchase/images/4/41/Another-Jin-Hyper.png",
		tierId: 12_000,
		type: "assault",
		tier: "T",
		attr: "retribution",
	},
	{
		id: 11_047,
		name: "Callisto",
		image: "https://static.wikia.nocookie.net/grandchase/images/7/7b/IconHero-Kalisto-Hyper.png",
		tierId: 12_000,
		type: "assault",
		tier: "SR",
		attr: "life",
	},
	{
		id: 11_048,
		name: "Myst",
		image: "https://static.wikia.nocookie.net/grandchase/images/0/0c/IconHero-Myst-Hyper.png",
		tierId: 12_000,
		type: "tank",
		tier: "SR",
		attr: "cycle",
	},
	{
		id: 11_049,
		name: "Nelia",
		image: "https://static.wikia.nocookie.net/grandchase/images/0/07/IconHero-Nelia-Hyper.png",
		tierId: 12_000,
		type: "mage",
		tier: "SR",
		attr: "ruin",
	},
	{
		id: 11_050,
		name: "Cindy",
		image: "https://static.wikia.nocookie.net/grandchase/images/9/9d/IconHero-NewCindy-Hyper.png",
		tierId: 12_000,
		type: "support",
		tier: "SR",
		attr: "retribution",
	},
	{
		id: 11_051,
		name: "Ragna",
		image: "https://static.wikia.nocookie.net/grandchase/images/9/9a/IconHero-Ragna-Hyper.png",
		tierId: 12_000,
		type: "ranged",
		tier: "SR",
		attr: "cycle",
	},
	{
		id: 11_052,
		name: "Rey (T)",
		image: "https://static.wikia.nocookie.net/grandchase/images/2/20/Another-Rey-Hyper.png",
		tierId: 12_000,
		type: "support",
		tier: "T",
		attr: "life",
	},
	{
		id: 11_053,
		name: "Ronan",
		image: "https://static.wikia.nocookie.net/grandchase/images/d/d5/IconHero-Ronan-Hyper.png",
		tierId: 12_000,
		type: "tank",
		tier: "SR",
		attr: "retribution",
	},
	{
		id: 11_054,
		name: "Ryan",
		image: "https://static.wikia.nocookie.net/grandchase/images/f/f7/IconHero-Ryan-Hyper.png",
		tierId: 12_000,
		type: "tank",
		tier: "SR",
		attr: "balance",
	},
	{
		id: 11_055,
		name: "Serdin",
		image: "https://static.wikia.nocookie.net/grandchase/images/f/f1/IconHero-Serdin-Hyper.png",
		tierId: 12_000,
		type: "support",
		tier: "SR",
		attr: "retribution",
	},
	{
		id: 11_056,
		name: "Sieghart (T)",
		image: "https://static.wikia.nocookie.net/grandchase/images/e/e3/Another-Sieghart-Hyper.png",
		tierId: 12_000,
		type: "tank",
		tier: "T",
		attr: "life",
	},
	{
		id: 11_057,
		name: "Sol",
		image: "https://static.wikia.nocookie.net/grandchase/images/d/df/IconHero-Sol-Hyper.png",
		tierId: 12_000,
		type: "assault",
		tier: "SR",
		attr: "retribution",
	},
	{
		id: 11_058,
		name: "Tia",
		image: "https://static.wikia.nocookie.net/grandchase/images/c/ca/IconHero-Tia-Hyper.png",
		tierId: 12_000,
		type: "tank",
		tier: "SR",
		attr: "life",
	},
	{
		id: 11_059,
		name: "Veigas (T)",
		image: "https://static.wikia.nocookie.net/grandchase/images/1/17/Another-Veigas-Hyper.png",
		tierId: 12_000,
		type: "ranged",
		tier: "T",
		attr: "retribution",
	},
	{
		id: 11_060,
		name: "Werner",
		image: "https://static.wikia.nocookie.net/grandchase/images/6/60/IconHero-Werner-Hyper.png",
		tierId: 12_000,
		type: "ranged",
		tier: "SR",
		attr: "life",
	},
	{
		id: 11_061,
		name: "Zero",
		image: "https://static.wikia.nocookie.net/grandchase/images/3/3a/IconHero-Zero-Hyper.png",
		tierId: 12_000,
		type: "tank",
		tier: "SR",
		attr: "ruin",
	},
	{
		id: 11_062,
		name: "Kanavan",
		image: "https://static.wikia.nocookie.net/grandchase/images/b/b7/IconHero-Kanavan-Hyper.png",
		tierId: 12_000,
		type: "assault",
		tier: "SR",
		attr: "retribution",
	},
	{
		id: 11_063,
		name: "Lapis",
		image: "https://static.wikia.nocookie.net/grandchase/images/3/38/IconHero-Lapis-Hyper.png",
		tierId: 12_000,
		type: "ranged",
		tier: "SR",
		attr: "life",
	},
	{
		id: 11_064,
		name: "Lass (T)",
		image: "https://static.wikia.nocookie.net/grandchase/images/1/1e/Another-Lass-Hyper.png",
		tierId: 12_000,
		type: "ranged",
		tier: "T",
		attr: "balance",
	},
	{
		id: 11_065,
		name: "Lime",
		image: "https://static.wikia.nocookie.net/grandchase/images/4/4a/IconHero-Lime-Hyper.png",
		tierId: 12_000,
		type: "support",
		tier: "SR",
		attr: "cycle",
	},
	{
		id: 11_066,
		name: "Rin",
		image: "https://static.wikia.nocookie.net/grandchase/images/d/dc/IconHero-Lin-Hyper.png",
		tierId: 12_000,
		type: "support",
		tier: "SR",
		attr: "cycle",
	},
	{
		id: 11_067,
		name: "Lire",
		image: "https://static.wikia.nocookie.net/grandchase/images/f/f0/IconHero-Lire-Hyper.png",
		tierId: 12_000,
		type: "ranged",
		tier: "SR",
		attr: "life",
	},
	{
		id: 11_068,
		name: "Rufus (T)",
		image: "https://static.wikia.nocookie.net/grandchase/images/1/1f/Another-Lupus-Hyper.png",
		tierId: 12_000,
		type: "mage",
		tier: "T",
		attr: "retribution",
	},
	{
		id: 11_069,
		name: "Nelia (T)",
		image: "https://static.wikia.nocookie.net/grandchase/images/3/38/Another-Nelia-Hyper.png",
		tierId: 12_000,
		type: "support",
		tier: "T",
		attr: "retribution",
	},
	{
		id: 11_070,
		name: "Asin (T)",
		image: "https://static.wikia.nocookie.net/grandchase/images/e/eb/Another-Azin-Hyper.png",
		tierId: 12_000,
		type: "assault",
		tier: "T",
		attr: "ruin",
	},
	{
		id: 11_071,
		name: "Arme (S)",
		image: "https://static.wikia.nocookie.net/grandchase/images/3/38/IconHero-Armx-Hyper.png",
		tierId: 12_000,
		type: "mage",
		tier: "SR",
		attr: "balance",
	},
	{
		id: 11_072,
		name: "Deia",
		image: "https://static.wikia.nocookie.net/grandchase/images/e/ef/IconHero-Deia-Hyper.png",
		tierId: 12_000,
		type: "ranged",
		tier: "SR",
		attr: "cycle",
	},
	{
		id: 11_073,
		name: "Tia (T)",
		image: "https://static.wikia.nocookie.net/grandchase/images/a/ae/Another-Tia-Hyper.png",
		tierId: 12_000,
		type: "assault",
		tier: "T",
		attr: "retribution",
	},
	{
		id: 11_074,
		name: "Ryan (T)",
		image: "https://static.wikia.nocookie.net/grandchase/images/f/f1/Another-Ryan-Hyper.png",
		tierId: 12_000,
		type: "mage",
		tier: "T",
		attr: "retribution",
	},
	{
		id: 11_075,
		name: "Urara",
		image: "https://static.wikia.nocookie.net/grandchase/images/4/4d/IconHero-Urara-Hyper.png",
		tierId: 12_000,
		type: "support",
		tier: "SR",
		attr: "life",
	},
	{
		id: 11_076,
		name: "Ganymede (T)",
		image: "https://static.wikia.nocookie.net/grandchase/images/7/73/Another-Ganymede-Hyper.png",
		tierId: 12_000,
		type: "ranged",
		tier: "T",
		attr: "balance",
	},
	{
		id: 11_077,
		name: "Dio (T)",
		image: "https://static.wikia.nocookie.net/grandchase/images/b/be/Another-Dio-Hyper.png",
		tierId: 12_000,
		type: "tank",
		tier: "T",
		attr: "cycle",
	},
	{
		id: 11_078,
		name: "Decanee (T)",
		image: "https://static.wikia.nocookie.net/grandchase/images/f/f9/Another-Decanee-Hyper.png",
		tierId: 12_000,
		type: "assault",
		tier: "T",
		attr: "balance",
	},
	{
		id: 11_079,
		name: "Myst (T)",
		image: "https://static.wikia.nocookie.net/grandchase/images/a/a4/Another-Myst-Hyper.png",
		tierId: 12_000,
		type: "mage",
		tier: "T",
		attr: "life",
	},
	{
		id: 11_080,
		name: "Uno (S)",
		image: "https://static.wikia.nocookie.net/grandchase/images/8/8c/IconHero-Unx-Hyper.png",
		tierId: 12_000,
		type: "ranged",
		tier: "SR",
		attr: "retribution",
	},
	{
		id: 11_081,
		name: "Vice",
		image: "https://static.wikia.nocookie.net/grandchase/images/8/81/IconHero-Vice-Hyper.png",
		tierId: 12_000,
		type: "mage",
		tier: "SR",
		attr: "balance",
	}
];
